package com.penwallet.roldechill.Entities;

public enum Status {
    NORMAL, ENVENENADO, CEGADO, DERRIBADO, ENSORDECIDO, HECHIZADO, INCAPACITADO, INCONSCIENTE, INVISIBLE, PARALIZADO, PETRIFICADO
}
